name: Main-Workflow

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: write-all

jobs:
  bump-dev-version: # only do that when actually merging in main/develop branch
    if: github.event_name != 'pull_request'
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/bump_dev_version_tag_branch.yaml@main
    with:
      app-id: ${{ vars.VERSION_BUMPER_APPID }}
    secrets:
      private-key: ${{ secrets.VERSION_BUMPER_SECRET }}

  # update-core-files:
  #   if: ${{ !cancelled() && github.event_name == 'pull_request' }}
  #   needs: [bump-dev-version]
  #   uses: ./.github/workflows/update-core-files.yaml

  R-CMD-Check:
    if: ${{ !cancelled() }}
    needs: [bump-dev-version]
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/R-CMD-check-build.yaml@main

  test-coverage:
    if: ${{ !cancelled() }}
    needs: [bump-dev-version]
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/test-coverage.yaml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


  pkgdown:
    if: ${{ !cancelled() }}
    needs: [bump-dev-version]
    uses:  Open-Systems-Pharmacology/Workflows/.github/workflows/pkgdown.yaml@main

