name: Main-Workflow

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]


jobs:
  increase-dev-version: # only do that when actually merging in main/develop branch
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/increase-dev-version.yaml
  R-CMD-Check:
    if: ${{ always() }}
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/R-CMD-check-build.yml@main
    with:
      install-pksim: true
      install-rClr: true
      extra-packages: |
        ospsuite.utils=github::Open-Systems-Pharmacology/OSPSuite.RUtils
        tlf=github::Open-Systems-Pharmacology/TLF-Library
  test-coverage:
    if: ${{ always() }}
    needs: [R-CMD-Check]
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/test-pkg-and-coverage.yml@main
    with:
      install-pksim: true
      install-rClr: true
      extra-packages: |
        ospsuite.utils=github::Open-Systems-Pharmacology/OSPSuite.RUtils
        tlf=github::Open-Systems-Pharmacology/TLF-Library
  pkgdown:
    if: ${{ always() }}
    needs: [R-CMD-Check]
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/pkgdown.yml@main
    with:
      install-pksim: true
      install-rClr: true
      extra-packages: |
        ospsuite.utils=github::Open-Systems-Pharmacology/OSPSuite.RUtils
        tlf=github::Open-Systems-Pharmacology/TLF-Library
