name: Main-Workflow

on:
  push:
    branches: [main]
  pull_request:


jobs:
  bump-dev-version: # only do that when actually merging in main/develop branch
    if: github.event_name != 'pull_request'
    uses: Felixmil/Workflows/.github/workflows/bump_dev_version_tag_branch.yaml@main
    with:
      app-id: ${{ vars.VERSION_BUMPER_APPID }}
      private-key: ${{ secrets.VERSION_BUMPER_SECRET }}

  update-core-files:
    if: ${{ !cancelled() && github.event_name == 'pull_request' }}
    needs: [bump-dev-version]
    uses: ./.github/workflows/update-core-files.yaml

  R-CMD-Check:
    if: ${{ !cancelled() }}
    needs: [update-core-files]
    uses: Felixmil/Workflows/.github/workflows/R-CMD-check-build.yaml@main

  test-coverage:
    if: ${{ !cancelled() }}
    needs: [update-core-files]
    uses: Felixmil/Workflows/.github/workflows/test-coverage.yaml@main

  pkgdown:
    if: ${{ !cancelled() }}
    needs: [update-core-files]
    uses:  Felixmil/Workflows/.github/workflows/pkgdown.yaml@main
