name: Update renv packages nightly

on:
  schedule:
    - cron: '0 2 * * *'  # Run at 2 AM UTC daily
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  update-renv-lock:
    runs-on: ubuntu-latest
    name: Update renv.lock

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install renv
        run: Rscript -e "install.packages('renv')"

      - name: Install packages from renv.locl at latest versions
        run: Rscript -e "renv::install(prompt = FALSE)"

      - name: Update renv.lock
        run: Rscript -e "renv::snapshot(prompt = FALSE, dev = TRUE)"

      - name: Upload updated renv.lock
        uses: actions/upload-artifact@v4
        with:
          name: renv-lock
          path: renv.lock
          retention-days: 1

  test-on-platforms:
    needs: update-renv-lock
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    name: Test on ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Download updated renv.lock
        uses: actions/download-artifact@v4
        with:
          name: renv-lock
          path: .

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install renv
        run: Rscript -e "install.packages(c('renv','devtools'))"

      - name: Restore renv environment
        run: Rscript -e "renv::restore(prompt = FALSE)"

      - name: Run R CMD Check
        run: Rscript -e "devtools::check(error_on = 'error')"

  commit-renv-lock:
    needs: test-on-platforms
    runs-on: ubuntu-latest
    if: needs.test-on-platforms.result == 'success'  # Only commit if tests pass on all platforms

    steps:
      - name: Generate token from GitHub App
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.VERSION_BUMPER_APPID }}  # Use GitHub App for authentication to trigger other workflows
          private-key: ${{ secrets.VERSION_BUMPER_SECRET }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Download updated renv.lock
        uses: actions/download-artifact@v4
        with:
          name: renv-lock
          path: .

      - name: Commit renv.lock if changed
        uses: EndBug/add-and-commit@v9
        with:
          message: 'ðŸ¤– Update renv.lock [skip actions]'
          default_author: github_actions
          add: 'renv.lock'
